/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 *****************************************************************************/

package com.salesforce.mcg.datasync.newbatch.data;

import lombok.*;

/**
 * Represents a range of subscriber phone numbers along with associated operator information.
 * Provides utility functionality to check if a phone number falls within this series range.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-03
 */
@Data
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class SubscriberSeries {

    /**
     * The starting phone number in the series (inclusive).
     */
    private Long seriesStart;

    /**
     * The ending phone number in the series (inclusive).
     */
    private Long seriesEnd;

    /**
     * The operator associated with this phone number series.
     */
    private String operator;

    /**
     * The virtual operator associated with this phone number series.
     */
    private String virtualOperator;

    /**
     * Determines whether the given phone number falls within the subscriber series range.
     *
     * @param phoneNumber the phone number to check
     * @return true if the phone number is within [seriesStart, seriesEnd], false otherwise
     */
    public boolean matches(Long phoneNumber) {
        if (phoneNumber == null || seriesStart == null || seriesEnd == null) {
            return false;
        }
        return phoneNumber >= seriesStart && phoneNumber <= seriesEnd;
    }
}

