/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.service;

import com.jcraft.jsch.ChannelSftp;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.Session;
import com.jcraft.jsch.SftpException;
import jakarta.annotation.Resource;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Vector;

/**
 * Service responsible for managing SFTP operations, specifically listing CSV files
 * from a given remote directory using a JSch SFTP channel.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-09
 */
@Component("dataSyncSftpService")
public class SFTPService {

    @Resource
    private Session session;

    /**
     * Lists the names of data files in the specified remote directory.
     * Now supports individual files (CSV, TXT, GZ) instead of ZIP files.
     *
     * @param remoteDir the path to the remote directory
     * @return a list of data file names found in the directory
     * @throws SftpException if an SFTP error occurs during listing
     */
    public List<String> listFiles(String remoteDir) throws SftpException, JSchException {
        if (!session.isConnected()){
            session.connect();
        }
        ChannelSftp sftp = (ChannelSftp) session.openChannel("sftp");
        sftp.connect();
        Vector<ChannelSftp.LsEntry> files = sftp.ls(remoteDir);
        return files.stream()
                .filter(f -> {
                    String filename = f.getFilename().toLowerCase();
                    return filename.endsWith(".csv") || 
                           filename.endsWith(".txt") || 
                           filename.endsWith(".gz") ||
                           filename.endsWith(".dat");
                })
                .map(ChannelSftp.LsEntry::getFilename)
                .toList();
    }

}
