spring.application.name=mcg-data-sync-app

spring.config.activate.on-profile=heroku

server.port=${SERVER_PORT}


spring.main.allow-bean-definition-overriding=true

spring.batch.jdbc.table-prefix=datasync_sch.batch_
spring.batch.job.enabled=false
spring.datasource.url=${DATABASE_URL}

sftp.data.host=${SFTP_DATA_HOST}
sftp.data.port=${SFTP_DATA_PORT}
sftp.data.username=${SFTP_DATA_USERNAME}
sftp.data.password=${SFTP_DATA_PASSWORD}
sftp.data.remote-dir=/
sftp.data.portados-series-subdir=${SFTP_DATA_PORTADOS_SERIES_SUBDIR:portados_series}
sftp.data.export-dir=${SFTP_DATA_EXPORT_DIR:/exports}
sftp.data.allow-unknown-keys=TRUE

logging.level.root=INFO
logging.level.com.salesforce.mcg.datasync=INFO
logging.level.org.springframework.batch.core.step.item.ChunkMonitor=ERROR
