spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never

spring.main.allow-bean-definition-overriding=true

spring.batch.jdbc.table-prefix=datasync_sch.batch_
spring.batch.job.enabled=false

logging.level.root=INFO
logging.level.com.salesforce.mcg.datasync=INFO
