spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never

spring.main.allow-bean-definition-overriding=true

spring.batch.jdbc.table-prefix=datasync_sch.batch_
spring.batch.job.enabled=false

sftp.default.out-dir=/
sftp.prod.out-dir=/export/
sftp.staging.out-dir=/export_staging/

logging.level.root=INFO
logging.level.com.salesforce.mcg.datasync=INFO
