/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 *****************************************************************************/

package com.salesforce.mcg.datasync.batch.sheet;


import com.salesforce.mcg.datasync.model.LineWithNumber;
import com.salesforce.mcg.datasync.model.Sheet;
import com.salesforce.mcg.datasync.repository.impl.SheetJdbcRepository;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.StepExecutionListener;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.scope.context.StepContext;
import org.springframework.batch.core.scope.context.StepSynchronizationManager;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.batch.item.ItemWriter;
import org.springframework.batch.item.database.JdbcBatchItemWriter;
import org.springframework.batch.item.database.builder.JdbcBatchItemWriterBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.transaction.PlatformTransactionManager;

import javax.sql.DataSource;
import java.util.*;

/**
 * Configuration class for Operator batch job.
 * Defines all necessary beans for reading, processing, and writing Operator records in a Spring Batch job.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-06
 */
@Configuration
public class SheetJob {

    /**
     * Creates the Job bean for Sheet import using multi-file tasklet.
     * Processes multiple sheet files (catalogo plantillas, 1 per company) as a single grouped job.
     *
     * @param jobRepository         the job repository
     * @param transactionManager    the transaction manager
     * @param stepExecutionListener the step execution listener
     * @return the configured Job
     */
    @Bean(name = "sheetJobBean")
    public Job sheetJob(JobRepository jobRepository,
                        PlatformTransactionManager transactionManager,
                        StepExecutionListener stepExecutionListener) {

        Step multiFileImportStep = new StepBuilder("sheetMultiFileImportStep", jobRepository)
                .tasklet(multiFileSheetTasklet(), transactionManager)
                .listener(stepExecutionListener)
                .build();

        return new JobBuilder("sheetJob", jobRepository)
                .start(multiFileImportStep)
                .build();
    }

    /**
     * Creates the MultiFileSheetTasklet bean with proper dependency injection.
     *
     * @return configured MultiFileSheetTasklet
     */
    @Bean
    public MultiFileSheetTasklet multiFileSheetTasklet() {
        return new MultiFileSheetTasklet();
    }


    /**
     * Transforms CSV lines into Operator objects using field mapping.
     *
     * @return the line-to-Operator processor
     */
    @StepScope
    @Bean
    public ItemProcessor<LineWithNumber, List<Sheet>> sheetProcessor() {
        return line -> {
            String company = companyName();
            String[] values = line.getLine().split(",", -1);
            Sheet tmpl_89992 = Sheet.builder()
                    .company(company)
                    .apiKey(values[0])
                    .shortCode("89992")
                    .smsName(values[1])
                    .build();
            Sheet tmpl_35000 = Sheet.builder()
                    .company(company)//Get from filename
                    .apiKey(values[0])
                    .shortCode("35000")
                    .smsName(values[3])
                    .build();
            Sheet tmpl_90120 = Sheet.builder()
                    .company(company)//Get from filename
                    .apiKey(values[0])
                    .shortCode("90120")
                    .smsName(values[5])
                    .build();
            return List.of(tmpl_89992, tmpl_35000, tmpl_90120);
        };
    }

    /**
     * Configures a JdbcBatchItemWriter for the Operator model.
     *
     * @param dataSource the datasource
     * @return the batch item writer
     */
    @Bean
    public JdbcBatchItemWriter<Sheet> sheetWriter(DataSource dataSource) {
        return new JdbcBatchItemWriterBuilder<Sheet>()
                .itemPreparedStatementSetter((item, ps) -> {
                    ps.setString(1, item.getCompany());
                    ps.setString(2, item.getApiKey());
                    ps.setString(3, item.getShortCode());
                    ps.setString(4, item.getSmsName());
                })
                .sql(SheetJdbcRepository.UPSERT_SQL)
                .dataSource(dataSource)
                .build();
    }

    // Spring Batch 5 signature
    @Bean
    public ItemWriter<List<Sheet>> flatteningWriter(JdbcBatchItemWriter<Sheet> delegate) {
        return itemsChunk -> {
            List<Sheet> flat = new ArrayList<>();
            for (List<Sheet> list : itemsChunk.getItems()) {
                if (list != null && !list.isEmpty()) flat.addAll(list);
            }
            if (!flat.isEmpty()) {
                delegate.write(org.springframework.batch.item.Chunk.of(flat.toArray(Sheet[]::new)));
            }
        };
    }

    private String companyName(){
        try {
            StepContext context = StepSynchronizationManager.getContext();
            Map<String, Object> params = Objects.requireNonNull(context).getJobParameters();
            String fileName = (String) params.get("fileName");
            if (Objects.nonNull(fileName)) {
                if (fileName.toLowerCase().startsWith("telnor")){
                    return "telnor";
                } else {
                    return "telmex";
                }
            } else {
                return "telmex";
            }
        } catch (Exception e) {
            return  null;
        }
    }
}