/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ***************************************************************************/

package com.salesforce.mcg.datasync.repository;

import com.salesforce.mcg.datasync.data.DataSyncConfig;

import java.util.Optional;

/**
 * Repository interface for managing {@link DataSyncConfig} persistence operations.
 * <p>
 * Defines methods for inserting, reading, and updating application configuration entities.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-06
 */
public interface DataSyncConfigRepository {

    /**
     * Inserts a new application configuration record.
     *
     * @param config the {@link DataSyncConfig} to insert
     * @return the number of records inserted (generally 1 if successful, 0 otherwise)
     */
    int insert(DataSyncConfig config);

    /**
     * Reads the application configuration.
     *
     * @return an {@link Optional} containing the {@link DataSyncConfig} if found, otherwise empty
     */
    Optional<DataSyncConfig> read();

    /**
     * Updates an existing application configuration record.
     *
     * @param config the {@link DataSyncConfig} to update
     * @return the number of records updated (generally 1 if successful, 0 otherwise)
     */
    int update(DataSyncConfig config);

}

