/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ***************************************************************************/

package com.salesforce.mcg.datasync.repository;

import com.salesforce.mcg.datasync.model.Operator;

import java.util.List;

/**
 * Repository interface for CRUD operations and batch processing for {@link Operator} entities.
 * <p>
 * Provides methods for single and batch insert, update, upsert, and delete operations,
 * as well as retrieval of Telcel or Telmex operator codes.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-05
 */
public interface OperatorRepository {

    /**
     * Retrieves a list of operator codes associated with Telcel or Telmex.
     *
     * @return a list of operator codes as {@link String}
     */
    List<String> findTelcelOrTelmexOperatorCodes();

    /**
     * Inserts a new {@link Operator} into the repository.
     *
     * @param op the operator to insert
     */
    void insert(Operator op);

    /**
     * Inserts a list of {@link Operator} entities into the repository in batch.
     *
     * @param list the list of operators to insert
     */
    void insertBatch(List<Operator> list);

    /**
     * Updates an existing {@link Operator} in the repository.
     *
     * @param op the operator to update
     */
    void update(Operator op);

    /**
     * Updates a list of {@link Operator} entities in the repository in batch.
     *
     * @param list the list of operators to update
     */
    void updateBatch(List<Operator> list);

    /**
     * Upserts (inserts or updates) an {@link Operator} in the repository.
     *
     * @param op the operator to upsert
     */
    void upsert(Operator op);

    /**
     * Upserts (inserts or updates) a list of {@link Operator} entities in batch.
     *
     * @param list the list of operators to upsert
     */
    void upsertBatch(List<Operator> list);

    /**
     * Deletes an {@link Operator} from the repository by operator ID.
     *
     * @param operatorId the unique identifier of the operator to delete
     */
    void delete(String operatorId);

    /**
     * Deletes a list of {@link Operator} entities in batch from the repository.
     *
     * @param list the list of operators to delete
     */
    void deleteBatch(List<Operator> list);
}

