/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 *****************************************************************************/

package com.salesforce.mcg.datasync.repository;

import com.salesforce.mcg.datasync.model.Sheet;

import java.util.List;

/**
 * Defines database access operations for Sheet entities.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-06
 */
public interface SheetRepository {

    Sheet getByApiKey(String company, String apiKey, String shortCode);

    List<Sheet> getByMainApiKey(String company, String mainApiKey);

    List<Sheet> findAll();
    /**
     * Inserts a new Sheet.
     *
     * @param sheet the sheet to insert
     */
    void insert(Sheet sheet);

    /**
     * Updates an existing Sheet.
     *
     * @param sheet the sheet to update
     */
    void update(Sheet sheet);

    /**
     * Performs an upsert operation (insert or update) for a Sheet.
     *
     * @param sheet the sheet to upsert
     */
    void upsert(Sheet sheet);

    /**
     * Inserts multiple Sheets in batch.
     *
     * @param sheets the list of Sheets to insert
     */
    void insertBatch(List<Sheet> sheets);

    /**
     * Removes all Sheets from the repository.
     */
    void truncate();

}

