/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 *****************************************************************************/

package com.salesforce.mcg.datasync.repository;

import com.salesforce.mcg.datasync.model.SubscriberPortability;

import java.util.List;
import java.util.Optional;

/**
 * Repository interface for handling CRUD operations and batch processes
 * for {@link SubscriberPortability} entities.
 *
 * <p>
 * Provides methods to insert, update, upsert, delete, and select subscriber portability data,
 * as well as batch operations and utility methods like truncating the table and retrieving cutoff dates.
 * </p>
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-08
 */
public interface SubscriberPortabilityRepository {

    /**
     * Inserts a new {@link SubscriberPortability} record.
     *
     * @param portability the portability record to insert
     */
    void insert(SubscriberPortability portability);

    /**
     * Inserts a batch of {@link SubscriberPortability} records.
     *
     * @param portabilityList the list of portability records to insert
     */
    void insertBatch(List<SubscriberPortability> portabilityList);

    /**
     * Updates an existing {@link SubscriberPortability} record.
     *
     * @param portability the portability record to update
     */
    void update(SubscriberPortability portability);

    /**
     * Updates a batch of {@link SubscriberPortability} records.
     *
     * @param portabilityList the list of portability records to update
     */
    void updateBatch(List<SubscriberPortability> portabilityList);

    /**
     * Inserts or updates a {@link SubscriberPortability} record.
     *
     * @param portability the portability record to upsert
     */
    void upsert(SubscriberPortability portability);

    /**
     * Inserts or updates a batch of {@link SubscriberPortability} records.
     *
     * @param portabilityList the list of portability records to upsert
     */
    void upsertBatch(List<SubscriberPortability> portabilityList);

    /**
     * Deletes a {@link SubscriberPortability} entry using phone number and operator.
     *
     * @param phoneNumber     the phone number of the subscriber
     * @param operator        the operator associated with the subscriber
     */
    void delete(Long phoneNumber, String operator);

    /**
     * Deletes a batch of {@link SubscriberPortability} entries.
     *
     * @param portabilityList the list of portability records to delete
     */
    void deleteBatch(List<SubscriberPortability> portabilityList);

    /**
     * Selects a {@link SubscriberPortability} by phone number.
     *
     * @param phoneNumber the phone number to search for
     * @return an {@link Optional} containing the matching record, if present
     */
    Optional<SubscriberPortability> selectByPhone(Long phoneNumber);

    /**
     * Selects {@link SubscriberPortability} entries by a collection of phone numbers.
     *
     * @param phoneNumbers the collection of phone numbers to search for
     * @return a list of matching portability records
     */
    List<SubscriberPortability> selectByPhones(List<Long> phoneNumbers);

    /**
     * Removes all entries from the subscriber portability table.
     */
    void truncateTable();

}

