/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.repository;

import com.salesforce.mcg.datasync.model.UploadedFile;

/**
 * Repository interface for performing CRUD operations on UploadedFile entities.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-11
 */
public interface UploadedFileRepository {
    /**
     * Inserts a new UploadedFile entity with the given filename and object identifier.
     *
     * @param filename the name of the file to insert
     * @param oid      the object identifier associated with the file
     * @return the unique id of the inserted uploaded file
     */
    long insert(String filename, long oid);

    /**
     * Retrieves an UploadedFile entity by its filename.
     *
     * @param filename the name of the file to search for
     * @return the UploadedFile corresponding to the given filename, or null if not found
     */
    UploadedFile getByFilename(String filename);

    /**
     * Deletes an UploadedFile entity by its filename.
     *
     * @param filename the name of the file to delete
     */
    void deleteByFilename(String filename);
}

