/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ***************************************************************************/

package com.salesforce.mcg.datasync.repository.impl;

import com.salesforce.mcg.datasync.model.Operator;
import com.salesforce.mcg.datasync.repository.DMLBatchOperation;
import com.salesforce.mcg.datasync.repository.OperatorRepository;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;

/**
 * JDBC implementation of the {@link OperatorRepository} for managing Operator data within the database.
 * <p>
 * Provides CRUD and batch operations using Spring's JdbcTemplate.
 * </p>
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-09
 */
@Repository
public class OperatorJdbcRepository implements OperatorRepository {

    public static final String INSERT_SQL =
            "insert into datasync_sch.operator (operator, name, type, rao, master_account, additional_master_account, virtual_operator, dual_operator, master_account_11, master_account_16, master_account_telnor, id_rvta_mayorista, idx) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
    public static final String UPDATE_SQL =
            "update datasync_sch.operator set operator = ?, name = ?, type = ?, rao = ?, master_account = ?, additional_master_account = ?, virtual_operator = ?, dual_operator = ?, master_account_11 = ?, master_account_16 = ?, master_account_telnor = ?, id_rvta_mayorista = ?, idx = ? where operator = ?";
    public static final String UPSERT_SQL =
            "insert into datasync_sch.operator (operator, name, type, rao, master_account, additional_master_account, virtual_operator, dual_operator, master_account_11, master_account_16, master_account_telnor, id_rvta_mayorista, idx) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on conflict (operator) do update set operator = excluded.operator, name = excluded.operator, type = excluded.type, master_account = excluded.master_account, additional_master_account = excluded.additional_master_account, dual_operator = excluded.dual_operator, virtual_operator = excluded.virtual_operator, master_account_11 = excluded.master_account_11, master_account_16 = excluded.master_account_16, master_account_telnor = excluded.master_account_telnor, id_rvta_mayorista = excluded.id_rvta_mayorista, idx = excluded.idx";
    public static final String DELETE_SQL =
            "delete from datasync_sch.operator where operator = ?";
    public static final String FIND_TELCEL_SQL =
            "select operator from datasync_sch.operator where lower(name) like '%telcel%' or lower(name) like '%telmex%'";

    private final JdbcTemplate jdbc;

    /**
     * Constructs a new {@code OperatorJdbcRepository} with the specified JdbcTemplate.
     *
     * @param jdbc the {@link JdbcTemplate} to use for JDBC operations
     */
    public OperatorJdbcRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<String> findTelcelOrTelmexOperatorCodes() {
        return jdbc.queryForList(FIND_TELCEL_SQL, String.class);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void insert(Operator op) {
        jdbc.update(INSERT_SQL,
                op.getOperator(),
                op.getName(),
                op.getType(),
                op.getRao(),
                op.getMasterAccount(),
                op.getAdditionalMasterAccount(),
                op.getVirtualOperator(),
                op.getDualOperator(),
                op.getMasterAccount11(),
                op.getMasterAccount16(),
                op.getMasterAccountTelnor(),
                op.getIdRvtaMayorista(),
                op.getIdx());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void insertBatch(List<Operator> list) {
        jdbc.batchUpdate(INSERT_SQL, new BatchSetter(list, DMLBatchOperation.INSERT));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void update(Operator op) {
        jdbc.update(UPDATE_SQL,
                op.getOperator(),
                op.getName(),
                op.getType(),
                op.getRao(),
                op.getMasterAccount(),
                op.getAdditionalMasterAccount(),
                op.getVirtualOperator(),
                op.getDualOperator(),
                op.getMasterAccount11(),
                op.getMasterAccount16(),
                op.getMasterAccountTelnor(),
                op.getIdRvtaMayorista(),
                op.getIdx(),
                op.getOperator());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void updateBatch(List<Operator> list) {
        jdbc.batchUpdate(UPDATE_SQL, new BatchSetter(list, DMLBatchOperation.UPDATE));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void upsert(Operator op) {
        jdbc.update(UPSERT_SQL,
                op.getOperator(),
                op.getName(),
                op.getType(),
                op.getRao(),
                op.getMasterAccount(),
                op.getAdditionalMasterAccount(),
                op.getVirtualOperator(),
                op.getDualOperator(),
                op.getMasterAccount11(),
                op.getMasterAccount16(),
                op.getMasterAccountTelnor(),
                op.getIdRvtaMayorista(),
                op.getIdx());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void upsertBatch(List<Operator> list) {
        jdbc.batchUpdate(UPSERT_SQL, new BatchSetter(list, DMLBatchOperation.UPSERT));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void delete(String operator) {
        jdbc.update(DELETE_SQL, operator);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void deleteBatch(List<Operator> list) {
        jdbc.batchUpdate(DELETE_SQL, new BatchSetter(list, DMLBatchOperation.DELETE));
    }

    /**
     * Helper class for batch operations on {@link Operator} entities.
     */
    public static class BatchSetter implements BatchPreparedStatementSetter {

        private final List<Operator> list;
        private final DMLBatchOperation operation;

        /**
         * Constructs a new {@code BatchSetter} for the given Operator list and batch operation.
         *
         * @param list      the list of Operator entities
         * @param operation the batch DML operation
         */
        public BatchSetter(List<Operator> list, @NonNull DMLBatchOperation operation) {
            this.list = list;
            this.operation = operation;
        }

        @Override
        public void setValues(@NonNull PreparedStatement ps, int i) throws SQLException {
            Operator op = list.get(i);
            if (DMLBatchOperation.INSERT.equals(operation)
                    || DMLBatchOperation.UPSERT.equals(operation)) {
                setInsertUpsertValues(ps, op);
            } else if (DMLBatchOperation.UPDATE.equals(operation)) {
                setUpdateValues(ps, op);
            } else if (DMLBatchOperation.DELETE.equals(operation)) {
                ps.setString(1, op.getOperator());
            } else {
                throw new IllegalArgumentException("Unsupported batch operation: " + operation);
            }
        }

        @Override
        public int getBatchSize() {
            return list.size();
        }

        /**
         * Sets values for INSERT or UPSERT statements.
         *
         * @param ps the {@link PreparedStatement}
         * @param op the {@link Operator}
         * @throws SQLException if an error occurs when setting parameters
         */
        private void setInsertUpsertValues(PreparedStatement ps, Operator op) throws SQLException {
            ps.setString(1, op.getOperator());
            ps.setString(2, op.getName());
            ps.setString(3, op.getType());
            ps.setString(4, op.getRao());
            ps.setString(5, op.getMasterAccount());
            ps.setString(6, op.getAdditionalMasterAccount());
            ps.setString(7, op.getVirtualOperator());
            ps.setString(8, op.getDualOperator());
            ps.setString(9, op.getMasterAccount11());
            ps.setString(10, op.getMasterAccount16());
            ps.setString(11, op.getMasterAccountTelnor());
            ps.setString(12, op.getIdRvtaMayorista());
            ps.setString(13, op.getIdx());
        }

        /**
         * Sets values for UPDATE statements.
         *
         * @param ps the {@link PreparedStatement}
         * @param op the {@link Operator}
         * @throws SQLException if an error occurs when setting parameters
         */
        private void setUpdateValues(PreparedStatement ps, Operator op) throws SQLException {
            setInsertUpsertValues(ps, op);
            ps.setString(14, op.getOperator());
        }
    }
}

