/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ******************************************************************************/

package com.salesforce.mcg.datasync.repository.impl;

import com.salesforce.mcg.datasync.model.Sheet;
import com.salesforce.mcg.datasync.repository.SheetRepository;
import jakarta.annotation.Resource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.ParameterizedPreparedStatementSetter;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;

/**
 * Implementation of the TemplateRepository interface for database operations related to the Template entity.
 *
 * <p>This class provides CRUD and search operations leveraging Spring's JdbcTemplate.</p>
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-07
 */
@Repository
public class SheetJdbcRepository implements SheetRepository {

    public static final String INSERT_SQL =
            "INSERT INTO datasync_sch.sheet (company, api_key, short_code, main_api_key, sms_name) VALUES (?, ?, ?, ?, ?)";

    public static final String UPDATE_SQL =
            "UPDATE  datasync_sch.sheet SET company = ?, api_key = ?, short_code = ?, main_api_key = ?, sms_name = ? WHERE company = ? AND api_key = ? AND short_code = ?";

    public static final String UPSERT_SQL =
            "INSERT INTO datasync_sch.sheet (company, api_key, short_code, main_api_key, sms_name) VALUES (?, ?, ?, ?, ?) " +
                    "ON CONFLICT (company, api_key, short_code) DO UPDATE SET sms_name = excluded.sms_name, main_api_key = excluded.main_api_key";

    public static final String TRUNCATE_SQL =
            "TRUNCATE TABLE datasync_sch.sheet CASCADE";

    public static final String GET_BY_APIKEY_SQL =
            "SELECT * FROM datasync_sch.sheet WHERE company = ? AND api_key = ? AND short_code = ?";

    public static final String GET_BY_MAIN_APIKEY_SQL =
            "SELECT * FROM datasync_sch.sheet WHERE company = ? AND main_api_key = ?";

    public static final String FIND_ALL_SQL =
            "SELECT * FROM datasync_sch.sheet";

    private final RowMapper<Sheet> sheetRowMapper = new TemplateRowMapper();

    @Resource
    private JdbcTemplate jdbcTemplate;

    /**
     * Retrieves a Template by its code.
     *
     * @param apiKey the api key of the template.
     * @param shortCode the code of the template.
     * @return an Optional containing the found Template if exists.
     */
    @Override
    public Sheet getByApiKey(String company, String apiKey, String shortCode) {
        try {
            return jdbcTemplate.queryForObject(
                    GET_BY_APIKEY_SQL, sheetRowMapper, company, apiKey, shortCode);
        } catch (org.springframework.dao.EmptyResultDataAccessException e) {
            return null; // not found
        }
    }

    /**
     * Retrieves a Template by its code.
     *
     * @param company the main api key of the template.
     * @param mainApiKey the code of the template.
     * @return an Optional containing the found Template if exists.
     */
    @Override
    public List<Sheet> getByMainApiKey(String company, String mainApiKey) {
        return jdbcTemplate.query(
                GET_BY_MAIN_APIKEY_SQL, sheetRowMapper, company, mainApiKey);
    }

    @Override
    public List<Sheet> findAll() {
        return  jdbcTemplate.query(FIND_ALL_SQL, sheetRowMapper);
    }

    /**
     * Inserts a new Template into the database.
     *
     * @param template the Template to insert.
     */
    @Override
    public void insert(Sheet template) {
        jdbcTemplate.update(
                INSERT_SQL,
                template.getCompany(),
                template.getApiKey(),
                template.getShortCode(),
                template.getMainApiKey(),
                template.getSmsName()
        );
    }

    /**
     * Inserts a batch of Templates into the database.
     *
     * @param templates the list of Templates to insert.
     */
    @Override
    public void insertBatch(List<Sheet> templates) {
        jdbcTemplate.batchUpdate(
                INSERT_SQL,
                templates,
                1000,
                new Setter()
        );
    }

    /**
     * Updates an existing Template in the database.
     *
     * @param template the Template to update.
     */
    @Override
    public void update(Sheet template) {
        jdbcTemplate.update(
                UPDATE_SQL,
                template.getCompany(),
                template.getApiKey(),
                template.getShortCode(),
                template.getMainApiKey(),
                template.getSmsName(),
                template.getCompany(),
                template.getApiKey(),
                template.getShortCode()
        );
    }

    /**
     * Inserts or updates a Template in the database (upsert).
     *
     * @param template the Template to upsert.
     */
    @Override
    public void upsert(Sheet template) {
        jdbcTemplate.update(
                UPSERT_SQL,
                template.getCompany(),
                template.getApiKey(),
                template.getShortCode(),
                template.getMainApiKey(),
                template.getSmsName()
        );
    }

    /**
     * Truncates the template table.
     */
    @Override
    public void truncate() {
        jdbcTemplate.execute(TRUNCATE_SQL);
    }

    /**
     * RowMapper implementation for mapping rows of ResultSet to Template objects.
     */
    public static class TemplateRowMapper implements RowMapper<Sheet> {
        @Override
        public Sheet mapRow(ResultSet rs, int rowNum) throws SQLException {

            return Sheet.builder()
                    .company(rs.getString("company"))
                    .apiKey(rs.getString("api_key"))
                    .mainApiKey(rs.getString("main_api_key"))
                    .shortCode(rs.getString("short_code"))
                    .smsName(rs.getString("sms_name")).build();
        }
    }

    public static class Setter implements ParameterizedPreparedStatementSetter<Sheet> {

        /**
         * @param ps prepared statement
         * @param sheet the object to persist
         * @throws SQLException thrown by method execution
         */
        @Override
        public void setValues(PreparedStatement ps, Sheet sheet) throws SQLException {

            ps.setString(1, sheet.getCompany());
            ps.setString(2, sheet.getApiKey());
            ps.setString(3, sheet.getShortCode());
            ps.setString(4, sheet.getMainApiKey());
            ps.setString(5, sheet.getSmsName());
        }
    }
}
