/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.repository.impl;

import com.salesforce.mcg.datasync.model.SubscriberSeries;
import com.salesforce.mcg.datasync.repository.DMLBatchOperation;
import com.salesforce.mcg.datasync.repository.SubscriberSeriesRepository;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Repository implementation for managing SubscriberSeries entities using JdbcTemplate.
 * <p>
 * Provides insert, update, upsert, delete, batch, and select operations for subscriber series.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-07
 */
@Repository
public class SubscriberSeriesJdbcRepository implements SubscriberSeriesRepository {

    public static final String UPSERT_SQL =
            "insert into datasync_sch.subscriber_series (series_start, series_end, operator, virtual_operator) values (?, ?, ?, ?) " +
                    "on conflict (series_start, series_end) do update set operator = excluded.operator, virtual_operator = excluded.virtual_operator";
    private static final String INSERT_SQL =
            "insert into datasync_sch.subscriber_series (series_start, series_end, operator, virtual_operator) values (?, ?, ?, ?)";
    private static final String UPDATE_SQL =
            "update datasync_sch.subscriber_series set operator = ?, virtual_operator = ? where series_start = ? and series_end = ?";
    private static final String DELETE_SQL =
            "delete from datasync_sch.subscriber_series where series_start = ?";
    private static final String TRUNCATE_SQL =
            "truncate datasync_sch.subscriber_series";
    private static final String FIND_PHONE_NUMBER_SQL =
            "select series_start, series_end, operator, virtual_operator from datasync_sch.subscriber_series " +
                    "where ? between series_start and series_end limit 1";
    private static final String FIND_SERIES_BY_PHONE_NUMBER =
            "with params(val) as (values (10), (25), (60)) select s.* from datasync_sch.subscriber_series s  " +
                    "join params p on p.val between s.series_start and s.series_end;";

    private final JdbcTemplate jdbc;

    /**
     * Constructs a repository with the given JdbcTemplate.
     *
     * @param jdbc the JdbcTemplate for database operations
     */
    public SubscriberSeriesJdbcRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    /**
     * Inserts a new SubscriberSeries entity into the database.
     *
     * @param series the SubscriberSeries entity to insert
     */
    @Override
    public void insert(SubscriberSeries series) {
        jdbc.update(INSERT_SQL, series.getSeriesStart(), series.getSeriesEnd(), series.getOperator(), series.getVirtualOperator());
    }

    /**
     * Inserts a list of SubscriberSeries entities in batch.
     *
     * @param list the list of SubscriberSeries entities to insert
     */
    @Override
    public void insertBatch(List<SubscriberSeries> list) {
        jdbc.batchUpdate(INSERT_SQL, new BatchSetter(list, DMLBatchOperation.INSERT));
    }

    /**
     * Updates an existing SubscriberSeries entity in the database.
     *
     * @param series the SubscriberSeries entity to update
     */
    @Override
    public void update(SubscriberSeries series) {
        jdbc.update(UPDATE_SQL, series.getOperator(), series.getVirtualOperator(), series.getSeriesStart(), series.getSeriesEnd());
    }

    /**
     * Updates a list of SubscriberSeries entities in batch using upsert.
     *
     * @param list the list of SubscriberSeries entities to update
     */
    @Override
    public void updateBatch(List<SubscriberSeries> list) {
        jdbc.batchUpdate(UPSERT_SQL, new BatchSetter(list, DMLBatchOperation.UPDATE));
    }

    /**
     * Performs an upsert (insert or update) of a SubscriberSeries entity.
     *
     * @param series the SubscriberSeries entity to upsert
     */
    @Override
    public void upsert(SubscriberSeries series) {
        jdbc.update(UPSERT_SQL, series.getSeriesStart(), series.getSeriesEnd(), series.getOperator(), series.getVirtualOperator());
    }

    /**
     * Performs an upsert (insert or update) in batch of SubscriberSeries entities.
     *
     * @param list the list of SubscriberSeries entities to upsert
     */
    @Override
    public void upsertBatch(List<SubscriberSeries> list) {
        jdbc.batchUpdate(UPSERT_SQL, new BatchSetter(list, DMLBatchOperation.UPSERT));
    }

    /**
     * Deletes a SubscriberSeries entity based on the series start value.
     *
     * @param seriesStart the SubscriberSeries entity or start value to delete
     */
    @Override
    public void delete(SubscriberSeries seriesStart) {
        jdbc.update(DELETE_SQL, seriesStart);
    }

    /**
     * Deletes a list of SubscriberSeries entities in batch.
     *
     * @param list the list of SubscriberSeries entities to delete
     */
    @Override
    public void deleteBatch(List<SubscriberSeries> list) {
        jdbc.batchUpdate(DELETE_SQL, new BatchSetter(list, DMLBatchOperation.DELETE));
    }

    /**
     * Finds a SubscriberSeries entity matching the given phone number.
     *
     * @param phoneNumber the phone number to search
     * @return an Optional containing the matching SubscriberSeries, if present
     */
    @Override
    public Optional<SubscriberSeries> selectByPhone(long phoneNumber) {
        List<SubscriberSeries> result = jdbc.query(FIND_PHONE_NUMBER_SQL, new Mapper(), phoneNumber);
        return result.stream().findFirst();
    }

    /**
     * Finds SubscriberSeries entities for a collection of phone numbers.
     *
     * @param phoneNumbers the collection of phone numbers to search
     * @return the list of matching SubscriberSeries entities
     */
    @Override
    public List<SubscriberSeries> selectByPhones(List<Long> phoneNumbers) {
        List<SubscriberSeries> matches = new ArrayList<>();
        for (Long phone : phoneNumbers) {
            selectByPhone(phone).ifPresent(matches::add);
        }
        return matches;
    }

    /**
     * Truncates the subscriber_series table.
     */
    @Override
    public void truncateTable() {
        jdbc.execute(TRUNCATE_SQL);
    }

    /**
     * RowMapper implementation for mapping ResultSet rows to SubscriberSeries objects.
     */
    public static class Mapper implements RowMapper<SubscriberSeries> {
        @Override
        public SubscriberSeries mapRow(ResultSet rs, int rowNum) throws SQLException {
            return SubscriberSeries.builder()
                    .seriesStart(rs.getLong("series_start"))
                    .seriesEnd(rs.getLong("series_end"))
                    .operator(rs.getString("operator"))
                    .virtualOperator(rs.getString("virtual_operator"))
                    .build();
        }
    }

    /**
     * BatchPreparedStatementSetter implementation for batch operations on SubscriberSeries entities.
     */
    public static class BatchSetter implements BatchPreparedStatementSetter {

        private final List<SubscriberSeries> list;
        private final DMLBatchOperation operation;

        /**
         * Constructs a batch setter with the provided list and operation type.
         *
         * @param list      the list of SubscriberSeries
         * @param operation the batch operation type
         */
        public BatchSetter(List<SubscriberSeries> list, @NonNull DMLBatchOperation operation) {
            this.list = list;
            this.operation = operation;
        }

        @Override
        public void setValues(@NonNull PreparedStatement ps, int i) throws SQLException {
            SubscriberSeries portability = list.get(i);
            if (operation == DMLBatchOperation.INSERT || operation == DMLBatchOperation.UPSERT) {
                ps.setLong(1, portability.getSeriesStart());
                ps.setLong(2, portability.getSeriesEnd());
                ps.setString(3, portability.getOperator());
                ps.setString(4, portability.getVirtualOperator());
            } else if (operation == DMLBatchOperation.UPDATE) {
                ps.setString(1, portability.getOperator());
                ps.setString(2, portability.getVirtualOperator());
                ps.setLong(3, portability.getSeriesStart());
                ps.setLong(4, portability.getSeriesEnd());
            } else if (operation == DMLBatchOperation.DELETE) {
                ps.setLong(1, portability.getSeriesStart());
            }
        }

        @Override
        public int getBatchSize() {
            return list.size();
        }
    }
}

