/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.repository.impl;

import com.salesforce.mcg.datasync.model.SubscriberPortability;
import com.salesforce.mcg.datasync.repository.DMLBatchOperation;
import com.salesforce.mcg.datasync.repository.SubscriberPortabilityRepository;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Optional;

/**
 * JDBC-based implementation of the {@link SubscriberPortabilityRepository} interface,
 * providing CRUD operations and batch processing of subscriber portability data.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-08
 */
@Repository
public class SubscriberPortabilityJdbcRepository implements SubscriberPortabilityRepository {

    // SQL query constants:
    public static final String INSERT_SQL =
            "INSERT INTO datasync_sch.subscriber_portability (phone_number, operator) VALUES (?, ?)";
    public static final String UPDATE_SQL =
            "UPDATE datasync_sch.subscriber_portability SET operator = ? WHERE phone_number = ?";
    public static final String UPSERT_SQL =
            "INSERT INTO datasync_sch.subscriber_portability (phone_number, operator) VALUES (?, ?) ON CONFLICT (phone_number) DO UPDATE SET operator = excluded.operator;";
    public static final String TRUNCATE_SQL =
            "TRUNCATE datasync_sch.subscriber_portability";
    public static final String DELETE_SQL =
            "DELETE FROM datasync_sch.subscriber_portability WHERE phone_number = ? AND operator = ?";
    public static final String FIND_PHONE_NUMBER_SQL =
            "SELECT phone_number, operator FROM datasync_sch.subscriber_portability WHERE phone_number = ?";

    private final JdbcTemplate jdbcTemplate;

    /*
     * Constructs a repository with the given JdbcTemplate.
     *
     * @param jdbcTemplate the JDBC template (not null)
     */
    public SubscriberPortabilityJdbcRepository(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Insert a new SubscriberPortability record.
     *
     * @param portability the subscriber portability record to insert
     */
    @Override
    public void insert(SubscriberPortability portability) {
        jdbcTemplate.update(
                INSERT_SQL,
                portability.getPhoneNumber(),
                portability.getOperator()
        );
    }

    /**
     * Update an existing SubscriberPortability record.
     *
     * @param portability the subscriber portability record to update
     */
    @Override
    public void update(SubscriberPortability portability) {
        jdbcTemplate.update(
                UPDATE_SQL,
                portability.getOperator(),
                portability.getPhoneNumber()
        );
    }

    /**
     * Upsert a SubscriberPortability record (insert or update if exists).
     *
     * @param portability the subscriber portability record to upsert
     */
    @Override
    public void upsert(SubscriberPortability portability) {
        jdbcTemplate.update(
                UPSERT_SQL,
                portability.getPhoneNumber(),
                portability.getOperator()
        );
    }

    /**
     * Delete a SubscriberPortability record by phone number and operator.
     *
     * @param phoneNumber     the phone number
     * @param operator        the operator
     */
    @Override
    public void delete(Long phoneNumber, String operator) {
        jdbcTemplate.update(
                DELETE_SQL,
                phoneNumber,
                operator
        );
    }

    /**
     * Select a SubscriberPortability by phone number.
     *
     * @param phoneNumber the phone number
     * @return optional containing the found record or empty if not found
     */
    @Override
    public Optional<SubscriberPortability> selectByPhone(Long phoneNumber) {
        List<SubscriberPortability> list = jdbcTemplate.query(
                FIND_PHONE_NUMBER_SQL,
                new Mapper(),
                phoneNumber
        );
        return list.stream().findFirst();
    }

    /**
     * Select subscriber portabilities by a collection of phone numbers.
     *
     * @param phoneNumbers collection of phone numbers
     * @return list of matching subscriber portabilities
     */
    @Override
    public List<SubscriberPortability> selectByPhones(List<Long> phoneNumbers) {
        // Dynamically construct the IN clause for the number of parameters.
        Object[] params = phoneNumbers.toArray();
        StringBuilder inClause = new StringBuilder();
        if (params.length > 0) {
            inClause.append("?");
            inClause.append(",?".repeat(params.length - 1));
        }
        String sql = "SELECT phone_number, operator FROM datasync_sch.subscriber_portability WHERE phone_number IN (" + inClause + ")";
        return jdbcTemplate.query(sql, new SubscriberPortabilityJdbcRepository.Mapper(), params);
    }

    /**
     * Truncates the subscriber portability table.
     */
    @Override
    public void truncateTable() {
        jdbcTemplate.execute(TRUNCATE_SQL);
    }

    /**
     * Insert a batch of SubscriberPortability records.
     *
     * @param list list of portabilities to insert
     */
    @Override
    public void insertBatch(List<SubscriberPortability> list) {
        jdbcTemplate.batchUpdate(INSERT_SQL, new Setter(list, DMLBatchOperation.INSERT));
    }

    /**
     * Update a batch of SubscriberPortability records.
     *
     * @param list list of portabilities to update
     */
    @Override
    public void updateBatch(List<SubscriberPortability> list) {
        jdbcTemplate.batchUpdate(UPDATE_SQL, new Setter(list, DMLBatchOperation.UPDATE));
    }

    /**
     * Upsert a batch of SubscriberPortability records.
     *
     * @param list list of portabilities to upsert
     */
    @Override
    public void upsertBatch(List<SubscriberPortability> list) {
        jdbcTemplate.batchUpdate(UPSERT_SQL, new Setter(list, DMLBatchOperation.UPSERT));
    }

    /**
     * Delete a batch of SubscriberPortability records.
     *
     * @param list list of portabilities to delete
     */
    @Override
    public void deleteBatch(List<SubscriberPortability> list) {
        jdbcTemplate.batchUpdate(DELETE_SQL, new Setter(list, DMLBatchOperation.DELETE));
    }

    /**
     * Gets the latest cutoff date from the portability table.
     *
     * @return latest portability date, or null if table is empty
     */
    public Date getCutoffDate() {
        return jdbcTemplate.queryForObject(
                "SELECT MAX(portability_start) FROM datasync_sch.subscriber_portability",
                Date.class
        );
    }

    /**
     * RowMapper implementation for SubscriberPortability objects.
     */
    public static class Mapper implements RowMapper<SubscriberPortability> {
        @Override
        public SubscriberPortability mapRow(ResultSet rs, int rowNum) throws SQLException {
            return SubscriberPortability.builder()
                    .phoneNumber(rs.getLong("phone_number"))
                    .operator(rs.getString("operator"))
                    .build();
        }
    }

    /**
     * BatchPreparedStatementSetter implementation for batch operations.
     */
    public static class Setter implements BatchPreparedStatementSetter {

        private final List<SubscriberPortability> list;
        private final DMLBatchOperation operation;

        /**
         * Constructs a Setter for batch operations.
         *
         * @param list      list of subscriber portability records
         * @param operation DML operation type (INSERT, UPDATE, UPSERT, DELETE)
         */
        public Setter(List<SubscriberPortability> list, @NonNull DMLBatchOperation operation) {
            this.list = list;
            this.operation = operation;
        }

        @Override
        public void setValues(@NonNull PreparedStatement ps, int i) throws SQLException {
            SubscriberPortability portability = list.get(i);
            switch (operation) {
                case INSERT:
                case UPSERT:
                    ps.setLong(1, portability.getPhoneNumber());
                    ps.setString(2, portability.getOperator());
                    break;
                case UPDATE:
                    ps.setString(1, portability.getOperator());
                    ps.setLong(2, portability.getPhoneNumber());
                    break;
                case DELETE:
                    ps.setLong(1, portability.getPhoneNumber());
                    ps.setString(2, portability.getOperator());
                    break;
            }
        }

        @Override
        public int getBatchSize() {
            return list.size();
        }
    }
}
