/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 *****************************************************************************/

package com.salesforce.mcg.datasync.repository.impl;

import com.salesforce.mcg.datasync.model.UploadedFile;
import com.salesforce.mcg.datasync.repository.UploadedFileRepository;
import jakarta.annotation.Resource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Repository;

import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 * JDBC implementation of {@link UploadedFileRepository} for managing uploaded files
 * in the datasync.uploaded_files database table.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-10
 */
@Repository
public class UploadedFileJdbcRepository implements UploadedFileRepository {

    public static final String INSERT_SQL =
            "INSERT INTO datasync_sch.uploaded_files (filename, oid) VALUES (?,?)";
    public static final String UPSERT_SQL =
            "INSERT INTO datasync_sch.uploaded_files (filename, oid) VALUES (?,?) ON CONFLICT (filename) DO UPDATE set oid = excluded.oid";
    public static final String SELECT_SQL =
            "SELECT filename, oid FROM datasync_sch.uploaded_files WHERE filename=?";
    public static final String DELETE_SQL =
            "DELETE FROM datasync_sch.uploaded_files WHERE filename = ?";

    @Resource
    private JdbcTemplate jdbc;

    /**
     * Inserts a new uploaded file record into the database.
     *
     * @param filename the filename of the uploaded file
     * @param oid      the object id associated with the file
     * @return the generated key of the new record if available, otherwise 1L
     */
    @Override
    public long insert(String filename, long oid) {
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbc.update(con -> {
            PreparedStatement ps = con.prepareStatement(
                    UploadedFileJdbcRepository.UPSERT_SQL,
                    Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, filename);
            ps.setLong(2, oid);
            return ps;
        }, keyHolder);

        return ((Long) keyHolder.getKeys().get("oid"));
    }

    /**
     * Retrieves an {@link UploadedFile} by its filename.
     *
     * @param filename the filename to find
     * @return the uploaded file if found
     */
    @Override
    public UploadedFile getByFilename(String filename) {
        return jdbc.queryForObject(
                SELECT_SQL,
                (rs, rowNum) -> new UploadedFile(
                        rs.getString("filename"),
                        rs.getLong("oid")
                ),
                filename
        );
    }

    /**
     * Deletes an uploaded file record by its filename.
     *
     * @param filename the filename to delete
     */
    @Override
    public void deleteByFilename(String filename) {
        jdbc.update(DELETE_SQL, filename);
    }
}
