/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.batch;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import ch.qos.logback.classic.encoder.PatternLayoutEncoder;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.FileAppender;
import org.slf4j.LoggerFactory;

import java.nio.file.Files;
import java.nio.file.Paths;

/**
 * A factory class to create and provide SLF4J loggers that log to specific files.
 * The loggers are configured with a dedicated file appender and ensure that
 * the logs directory exists before writing logs.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-05
 */
public class FileLoggerFactory {

    /**
     * Retrieves or creates a logger that writes to the specified file.
     * Ensures the logger uses a dedicated appender per file and that the logs directory exists.
     *
     * @param fileName the name of the file to log to (relative to logs/)
     * @return the configured SLF4J Logger instance
     */
    public static org.slf4j.Logger getLoggerForFile(String fileName) {
        ensureLogsDirectoryExists();

        LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
        String loggerName = buildLoggerName(fileName);
        Logger logger = context.getLogger(loggerName);
        logger.setAdditive(false);

        String appenderName = buildAppenderName(fileName);

        if (logger.getAppender(appenderName) != null) {
            return logger;
        }

        PatternLayoutEncoder encoder = createPatternLayoutEncoder(context);
        FileAppender<ILoggingEvent> fileAppender = createFileAppender(context, encoder, appenderName, fileName);
        logger.addAppender(fileAppender);

        return logger;
    }

    /**
     * Ensures that the logs directory exists.
     * Throws a runtime exception if unable to create the directory.
     */
    private static void ensureLogsDirectoryExists() {
        try {
            Files.createDirectories(Paths.get("logs"));
        } catch (Exception e) {
            throw new RuntimeException("Failed to create logs directory", e);
        }
    }

    /**
     * Builds the logger name for a provided file name.
     *
     * @param fileName the base file name used for logging
     * @return the logger name
     */
    private static String buildLoggerName(String fileName) {
        return "fileLogger-" + fileName;
    }

    /**
     * Builds the appender name for a provided file name.
     *
     * @param fileName the base file name used for logging
     * @return the appender name
     */
    private static String buildAppenderName(String fileName) {
        return "FILE-" + fileName;
    }

    /**
     * Creates and configures a PatternLayoutEncoder for log formatting.
     *
     * @param context the Logback LoggerContext
     * @return a started PatternLayoutEncoder
     */
    private static PatternLayoutEncoder createPatternLayoutEncoder(LoggerContext context) {
        PatternLayoutEncoder encoder = new PatternLayoutEncoder();
        encoder.setContext(context);
        encoder.setPattern("%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n");
        encoder.start();
        return encoder;
    }

    /**
     * Creates and configures a FileAppender for the given file.
     *
     * @param context      the Logback LoggerContext
     * @param encoder      the layout encoder to use for formatting
     * @param appenderName the name of the appender
     * @param fileName     the name of the log file (relative to logs/)
     * @return a started FileAppender
     */
    private static FileAppender<ILoggingEvent> createFileAppender(
            LoggerContext context,
            PatternLayoutEncoder encoder,
            String appenderName,
            String fileName) {
        FileAppender<ILoggingEvent> fileAppender = new FileAppender<>();
        fileAppender.setContext(context);
        fileAppender.setName(appenderName);
        fileAppender.setFile("logs/file-" + fileName);
        fileAppender.setEncoder(encoder);
        fileAppender.start();
        return fileAppender;
    }
}