/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.batch;

import com.jcraft.jsch.Session;
import com.salesforce.mcg.datasync.sftp.SftpReadableResource;
import com.salesforce.mcg.datasync.model.LineWithNumber;
import com.salesforce.mcg.datasync.repository.DataSyncConfigRepository;
import com.salesforce.mcg.datasync.repository.SubscriberPortabilityRepository;
import lombok.extern.slf4j.Slf4j;
import org.springframework.batch.core.StepExecutionListener;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.item.file.FlatFileItemReader;
import org.springframework.batch.item.file.LineMapper;
import org.springframework.batch.item.file.builder.FlatFileItemReaderBuilder;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.task.TaskExecutor;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

/**
 * Spring Batch job configuration class for setting up SFTP channel,
 * job repository, step listener and task executor.
 *
 * <p>
 * Provides well-organized bean definitions and SFTP helper code to enable
 * robust and reliable batch operations for file transfers and data processing.
 * </p>
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-04
 */
@Configuration
@Slf4j
public class JobConfig {

    public static final String FILE_NAME = "fileName";
    public static final String COMPANY_NAME = "companyName";
    public static final String TABLE_NAME = "tableName";

    @Value("${sftp.data.host}")
    private String hostname;

    @Value("${sftp.data.port:22}")
    private Integer port;

    @Value("${sftp.data.username}")
    private String username;

    @Value("${sftp.data.password}")
    private String password;

    @Value("${sftp.data.allow-unknown-keys}")
    private Boolean allowUnknownKeys;

    @Value("${sftp.charset:'UTF-8'}")
    private String charset;

    /**
     * Defines a thread pool based {@link TaskExecutor} for parallel batch processing.
     *
     * @return a configured ThreadPoolTaskExecutor instance.
     */
    @Bean
    public TaskExecutor taskExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(4);
        executor.setMaxPoolSize(4);
        executor.setQueueCapacity(10);
        executor.setThreadNamePrefix("batch-thread-");
        executor.initialize();
        return executor;
    }

    /**
     * Provides a {@link StepExecutionListener} for moving files after them being successfully imported.
     *
     * @param session the SFTP channel to use for file movement
     * @return an implementation of StepExecutionListener
     */
    @Bean
    @StepScope
    public DataSyncStepExecutionListener stepExecutionListener(
            Session session,
            SubscriberPortabilityRepository repository,
            DataSyncConfigRepository configRepository) {
        return new DataSyncStepExecutionListener(repository, session, configRepository);
    }

    @Bean(name = "gzSftpAwareReader")
    @StepScope
    public FlatFileItemReader<LineWithNumber> gzSftpAwareReader(
            Session session,
            @Value("#{jobParameters['fileName']}") String file,
            LineMapper<LineWithNumber> lineMapper
    ) {
        return new FlatFileItemReaderBuilder<LineWithNumber>()
                .name("gzSftpAwareReader")
                .resource(new SftpReadableResource(session, file))
                .encoding("UTF-8")
                .linesToSkip(1)
                .saveState(true)
                .bufferedReaderFactory(new CompressBufferedReaderFactory())
                .lineMapper(lineMapper)
                .build();
    }

    @Bean(name = "gzBlobAwareReader")
    @StepScope
    public FlatFileItemReader<LineWithNumber> gzBlobAwareReader(
            LineMapper<LineWithNumber> lineMapper,
            LargeObjectResource largeObjectResource
    ) {
        return new FlatFileItemReaderBuilder<LineWithNumber>()
                .name("gzBlobAwareReader")
                .resource(largeObjectResource)
                .encoding("UTF-8")
                .linesToSkip(1)
                .saveState(true)
                .bufferedReaderFactory(new CompressBufferedReaderFactory())
                .lineMapper(lineMapper)
                .build();
    }


}