/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.batch;

import com.salesforce.mcg.datasync.model.LineWithNumber;
import org.springframework.batch.item.file.LineMapper;
import org.springframework.stereotype.Component;

/**
 * Maps each line from a file along with its line number to a {@link LineWithNumber} object.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-05
 */
@Component
public class NumberedLineMapper implements LineMapper<LineWithNumber> {

    /**
     * Maps a single line and its number to a {@link LineWithNumber} instance.
     *
     * @param line       the content of the line
     * @param lineNumber the number of the line (starting at 1)
     * @return a new {@link LineWithNumber} object containing line number and content
     */
    @Override
    public LineWithNumber mapLine(String line, int lineNumber) {
        return new LineWithNumber(lineNumber, line);
    }
}
