/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ***************************************************************************/

package com.salesforce.mcg.datasync.model;

import java.util.Objects;

/**
 * Represents a line with its corresponding line number.
 *
 * <p>
 * This POJO is commonly used to encapsulate a line of text together with its
 * line number in the context of processing text files or logs.
 * </p>
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-09
 */
public class LineWithNumber {

    /**
     * The line number associated with the line.
     */
    private long lineNumber;

    /**
     * The content of the line.
     */
    private String line;

    // Constructors
    public LineWithNumber() {
    }

    public LineWithNumber(long lineNumber, String line) {
        this.lineNumber = lineNumber;
        this.line = line;
    }

    // Builder pattern
    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private long lineNumber;
        private String line;

        public Builder lineNumber(long lineNumber) {
            this.lineNumber = lineNumber;
            return this;
        }

        public Builder line(String line) {
            this.line = line;
            return this;
        }

        public LineWithNumber build() {
            return new LineWithNumber(lineNumber, line);
        }
    }

    // Getters and Setters
    public long getLineNumber() {
        return lineNumber;
    }

    public void setLineNumber(long lineNumber) {
        this.lineNumber = lineNumber;
    }

    public String getLine() {
        return line;
    }

    public void setLine(String line) {
        this.line = line;
    }

    // toString
    @Override
    public String toString() {
        return "LineWithNumber{" +
                "lineNumber=" + lineNumber +
                ", line='" + line + '\'' +
                '}';
    }

    // equals and hashCode (based on lineNumber only as per original @EqualsAndHashCode(of = "lineNumber"))
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        LineWithNumber that = (LineWithNumber) o;
        return lineNumber == that.lineNumber;
    }

    @Override
    public int hashCode() {
        return Objects.hash(lineNumber);
    }
}

