/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.model;

import lombok.*;

/**
 * Represents an Operator entity with various account and operator-related details.
 *
 * <p>This class acts as a model for holding operator information, such as IDs and account references.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-10
 */
@Data
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Operator {

    /**
     * The operator code or identifier.
     */
    private String operator;

    /**
     * The name of the operator.
     */
    private String name;

    /**
     * The type/category of the operator.
     */
    private String type;

    /**
     * The RAO (Administrative Organization Registry or other code).
     */
    private String rao;

    /**
     * The main/master account associated with the operator.
     */
    private String masterAccount;

    /**
     * An additional master account associated with the operator.
     */
    private String additionalMasterAccount;

    /**
     * The virtual operator attribute.
     */
    private String virtualOperator;

    /**
     * Indicates dual operator status.
     */
    private String dualOperator;

    /**
     * The master account 11 reference.
     */
    private String masterAccount11;

    /**
     * The master account 16 reference.
     */
    private String masterAccount16;

    /**
     * The Telnor-specific master account reference.
     */
    private String masterAccountTelnor;

    /**
     * The wholesale sale ID related to the operator.
     */
    private String idRvtaMayorista;

    /**
     * The index or order reference for the operator.
     */
    private String idx;
}

