/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.model;

import lombok.*;


/**
 * Represents an SMS template configuration for a specific company and provider.
 *
 * <p>
 * This class contains information such as the company name, template code,
 * API key, SMS name, and whether the template is for the Telcel provider.
 * </p>
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-04
 */
@Data
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Sheet {

    /**
     * The name of the company this template is associated with.
     */
    private String company;

    /**
     * The api key
     */
    private String apiKey;

    /**
     * The API key for interacting with the template service.
     */
    private String shortCode;

    /**
     * Main Api key
     */
    private String mainApiKey;

    /**
     * The SMS template name.
     */
    private String smsName;

}

