/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.model;

import lombok.*;
import java.util.Date;

/**
 * Represents the portability details for a subscriber, including phone number,
 * operator, and the date of portability.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-06
 */
@Data
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class SubscriberPortability {

    /**
     * The phone number of the subscriber.
     */
    private Long phoneNumber;

    /**
     * The operator currently associated with the subscriber.
     */
    private String operator;

    /**
     * The start date of portability (when the portability became active).
     * This field is used for staging table processing only.
     */
    private Date portabilityStart;

    /**
     * The end date of portability (when the portability was deactivated).
     * This field is used for staging table processing only.
     * Null indicates the portability is still active.
     */
    private Date portabilityEnd;
}

