/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

 package com.salesforce.mcg.datasync.batch.portability;

import com.jcraft.jsch.ChannelSftp;
import com.jcraft.jsch.Session;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
 import org.postgresql.copy.CopyManager;
 import org.postgresql.core.BaseConnection;
 import org.springframework.batch.core.StepContribution;
 import org.springframework.batch.core.scope.context.ChunkContext;
 import org.springframework.batch.core.step.tasklet.Tasklet;
 import org.springframework.batch.repeat.RepeatStatus;
 
 import javax.sql.DataSource;
 import java.io.*;
import java.sql.Connection;
import java.sql.Statement;
 import java.util.concurrent.atomic.AtomicLong;
 import java.util.zip.GZIPInputStream;
 
 /**
  * High-performance tasklet that streams subscriber portability data directly from SFTP
  * to a PostgreSQL staging table using the COPY command.
  *
  * This tasklet implements the first stage of a high-volume ETL process:
  * 1. TRUNCATE the staging table.
  * 2. COPY the full dataset from SFTP into the staging table.
  * A subsequent step should be used to MERGE the data from staging into the final production table.
  *
  * @author Salesforce Proserv Team
  * @generated by AI
  * @since 2025-01-09
  */
 @Slf4j
 @RequiredArgsConstructor
 public class PostgresCopyTasklet implements Tasklet {
 
 
     private final DataSource dataSource;
     private final Session sftpSession;
 
    @Override
    public RepeatStatus execute(@NonNull StepContribution contribution, @NonNull ChunkContext chunkContext) throws Exception {
         String[] files = chunkContext.getStepContext().getJobParameters().get("fileName").toString().split(",");
         log.info("Starting optimized PostgreSQL COPY import for {} files: {}", files.length, String.join(", ", files));
 
         AtomicLong totalLinesRead = new AtomicLong(0);
         AtomicLong recordsForCopy = new AtomicLong(0);
         AtomicLong skippedRecords = new AtomicLong(0);
 
         long startTime = System.currentTimeMillis();
 
         try (Connection connection = dataSource.getConnection()) {
             // Step 1: Truncate the staging table before loading new data.
             log.info("Truncating staging table: datasync_sch.subscriber_portability_staging");
             try (Statement stmt = connection.createStatement()) {
                 stmt.execute("TRUNCATE TABLE datasync_sch.subscriber_portability_staging");
             }
 
             // Unwrap connection to get the underlying PostgreSQL connection for CopyManager
             BaseConnection pgConnection = connection.unwrap(BaseConnection.class);
             CopyManager copyManager = new CopyManager(pgConnection);
 
            String copySQL = "COPY datasync_sch.subscriber_portability_staging " +
                           "(phone_number, operator) FROM STDIN WITH (FORMAT CSV)";
 
             // Use Piped streams to connect the data processing thread to the COPY thread
             PipedInputStream pipedInput = new PipedInputStream(1024 * 1024); // 1MB buffer
             PipedOutputStream pipedOutput = new PipedOutputStream(pipedInput);
 
             // Start the PostgreSQL COPY operation in a separate thread.
             // It will block waiting for data from the PipedInputStream.
             Thread copyThread = new Thread(() -> {
                 try {
                     long copiedRecords = copyManager.copyIn(copySQL, pipedInput);
                     log.info("PostgreSQL COPY thread finished. {} records were ingested by the database.", copiedRecords);
                 } catch (Exception e) {
                     log.error("Error during PostgreSQL COPY operation. The data stream is likely corrupted.", e);
                     // This is a fatal error, re-throw to fail the step
                     throw new RuntimeException("COPY operation failed", e);
                 }
             });
             copyThread.start();
 
 
             // Main thread: read from SFTP, process, and write to the PipedOutputStream
             try (PrintWriter writer = new PrintWriter(new OutputStreamWriter(pipedOutput, "UTF-8"))) {
                 ChannelSftp sftp = (ChannelSftp) sftpSession.openChannel("sftp");
                 sftp.connect();
 
                 for (String fileName : files) {
                     processFile(fileName.trim(), sftp, writer, totalLinesRead, recordsForCopy, skippedRecords);
                 }
 
                 if (sftp.isConnected()) {
                     sftp.disconnect();
                 }
             } finally {
                 // IMPORTANT: Close the writer and output stream to signal the end of data to the copyThread.
                 pipedOutput.close();
             }
 
             // Wait for the COPY thread to complete its work
             copyThread.join();
 
         } catch (Exception e) {
             log.error("A critical error occurred during the data import tasklet.", e);
             throw e; // Fail the job
         }
 
        long durationSeconds = (System.currentTimeMillis() - startTime) / 1000;
        log.info("Optimized import process finished in {} seconds (~{} minutes).", durationSeconds, durationSeconds / 60);
        log.info("Summary: Total Lines Read={}, Records for COPY={}, Records Skipped={}",
                totalLinesRead.get(), recordsForCopy.get(), skippedRecords.get());

        // Update step contribution with statistics efficiently
        try {
            // Use reflection to set the counts directly for better performance
            java.lang.reflect.Field readCountField = contribution.getClass().getDeclaredField("readCount");
            readCountField.setAccessible(true);
            readCountField.set(contribution, totalLinesRead.get());
            
            java.lang.reflect.Field writeCountField = contribution.getClass().getDeclaredField("writeCount");
            writeCountField.setAccessible(true);
            writeCountField.set(contribution, recordsForCopy.get());
            
            java.lang.reflect.Field processSkipCountField = contribution.getClass().getDeclaredField("processSkipCount");
            processSkipCountField.setAccessible(true);
            processSkipCountField.set(contribution, skippedRecords.get());
            
            log.info("Updated Spring Batch statistics: Read={}, Write={}, ProcessSkip={}", 
                    totalLinesRead.get(), recordsForCopy.get(), skippedRecords.get());
                    
        } catch (Exception reflectionError) {
            log.warn("Could not update Spring Batch statistics via reflection: {}", reflectionError.getMessage());
            // Fallback to increment methods (less efficient but functional)
            contribution.incrementWriteCount(recordsForCopy.get());
            log.info("Fallback statistics update: Write={}, Actual Read={}, ProcessSkip={}", 
                    recordsForCopy.get(), totalLinesRead.get(), skippedRecords.get());
        }

        return RepeatStatus.FINISHED;
     }
 
     private void processFile(String fileName, ChannelSftp sftp, PrintWriter writer, AtomicLong totalLinesRead, AtomicLong recordsForCopy, AtomicLong skippedRecords) throws Exception {
         log.info("Processing file: {}", fileName);
         long fileLines = 0;
 
         try (InputStream sftpStream = sftp.get(fileName);
              InputStream decompressedStream = fileName.toLowerCase().endsWith(".gz") ? new GZIPInputStream(sftpStream) : sftpStream;
              Reader streamReader = new InputStreamReader(decompressedStream, "UTF-8");
              CSVReader csvReader = new CSVReader(streamReader)) {
 
             String[] headers = csvReader.readNext(); // Read header line
             if (headers == null) {
                 log.warn("File {} is empty or invalid.", fileName);
                 return;
             }
 
             // Find column indices once
             int phoneIndex = findColumnIndex(headers, "TELEFONO_PORTADO");
             int operatorIndex = findColumnIndex(headers, "OPERADOR");
             int startIndex = findColumnIndex(headers, "FECHA_ALTA");
             int endIndex = findColumnIndex(headers, "FECHA_BAJA");
 
             String[] line;
             while ((line = csvReader.readNext()) != null) {
                 totalLinesRead.incrementAndGet();
                 fileLines++;
 
                 String processedCsvLine = processLine(line, phoneIndex, operatorIndex, startIndex, endIndex);
                 if (processedCsvLine != null) {
                     writer.println(processedCsvLine);
                     recordsForCopy.incrementAndGet();
                 } else {
                     skippedRecords.incrementAndGet();
                 }
                 
                 if (fileLines % 1_000_000 == 0) {
                     log.info("...processed {} lines from {}", fileLines, fileName);
                 }
             }
         } catch (CsvValidationException e) {
             log.error("CSV validation error in file {} at line {}: {}", fileName, e.getLineNumber(), e.getMessage());
             throw e;
         }
         log.info("Finished processing file: {}. Total lines in file: {}", fileName, fileLines);
     }
 
    /**
     * Processes a single line from the CSV file.
     * Returns a formatted CSV string for the COPY command or null if the record should be skipped.
     */
    private String processLine(String[] values, int phoneIdx, int operatorIdx, int startIdx, int endIdx) {
        // Core business rule: must have start date and no end date
        String portabilityStartStr = values[startIdx];
        String portabilityEndStr = values[endIdx];
        
        // Skip if no start date or has end date
        if (portabilityStartStr == null || portabilityStartStr.trim().isEmpty() ||
            (portabilityEndStr != null && !portabilityEndStr.trim().isEmpty())) {
            return null;
        }

        String phoneNumberStr = values[phoneIdx];
        String operatorStr = values[operatorIdx];
        
        // Skip if required fields are missing
        if (phoneNumberStr == null || phoneNumberStr.trim().isEmpty() || 
            operatorStr == null || operatorStr.trim().isEmpty()) {
            return null;
        }

        // Simple format: phone_number,operator
        // Only include phone number and operator - start date is used for filtering only
        return String.format("52%s,%s",
                phoneNumberStr.trim(),
                escapeCsvValue(operatorStr.trim())
        );
    }
     
 
     /**
      * Finds the index of a column in the header array (case-insensitive).
      */
     private int findColumnIndex(String[] headers, String columnName) {
         for (int i = 0; i < headers.length; i++) {
             if (headers[i].trim().equalsIgnoreCase(columnName)) {
                 return i;
             }
         }
         throw new IllegalArgumentException("Required header column not found: " + columnName);
     }
 
     /**
      * Escapes a string value for inclusion in a CSV field for PostgreSQL COPY.
      * Handles commas, quotes, and newlines.
      */
     private String escapeCsvValue(String value) {
         if (value == null) return "";
         // If the value contains a comma, double-quote, or newline, it must be enclosed in double-quotes.
         // Any existing double-quotes within the value must be escaped by doubling them (e.g., " becomes "").
         if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
             return "\"" + value.replace("\"", "\"\"") + "\"";
         }
         return value;
     }
 }
