/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync;

import com.salesforce.mcg.datasync.common.SalesforceBanner;
import lombok.AllArgsConstructor;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

/**
 * Entry point for the Data Sync microservice application.
 * <p>
 * Bootstraps the Spring Boot application as a one-off dyno (no web server).
 * Jobs are triggered via command line parameters (--job=xxx) or scheduled externally via Heroku Scheduler.
 * </p>
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-09
 */
@SpringBootApplication
@ComponentScan(basePackages = {
        "com.salesforce.mcg.datasync"
})
@AllArgsConstructor
public class DataSyncApplication {

    /**
     * Main method to start the Spring Boot application.
     * Runs as a one-off dyno with no web server.
     *
     * @param args command line arguments (supports --job=xxx for specific job execution)
     */
    public static void main(String[] args) {
        SpringApplication app = new SpringApplication(DataSyncApplication.class);
        app.setWebApplicationType(org.springframework.boot.WebApplicationType.NONE);
        app.setBanner(new SalesforceBanner());
        app.setBannerMode(org.springframework.boot.Banner.Mode.CONSOLE);
        System.exit(SpringApplication.exit(app.run(args)));
    }
}
