/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.batch.series;

import com.jcraft.jsch.ChannelSftp;
import com.jcraft.jsch.Session;
import com.salesforce.mcg.datasync.model.SubscriberSeries;
import com.salesforce.mcg.datasync.repository.impl.SubscriberSeriesJdbcRepository;
import jakarta.annotation.Resource;
import lombok.extern.slf4j.Slf4j;
import org.springframework.batch.core.StepContribution;
import org.springframework.batch.core.scope.context.ChunkContext;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.concurrent.atomic.AtomicLong;
import java.util.Map;
import java.util.HashMap;

/**
 * Tasklet that processes multiple subscriber series files as a single grouped job.
 * This allows the 3 series files to be processed together as one logical unit.
 *
 * @author Salesforce Proserv Team
 * @generated by AI
 * @since 2025-09-16
 */
@Slf4j
@Component
public class MultiFileSeriesTasklet implements Tasklet {

    @Resource
    private Session sftpSession;

    @Autowired
    private DataSource dataSource;

    @Override
    public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {
        String fileNames = chunkContext.getStepContext().getJobParameters().get("fileName").toString();
        String[] files = fileNames.split(",");
        
        log.info("Processing {} series files as a grouped job: {}", files.length, java.util.Arrays.toString(files));
        
        AtomicLong totalRecords = new AtomicLong(0);
        AtomicLong processedRecords = new AtomicLong(0);
        AtomicLong skippedRecords = new AtomicLong(0);
        AtomicLong errorRecords = new AtomicLong(0);

        long startTime = System.currentTimeMillis();

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            
            // Use optimized batch processing with direct UPSERT
            String sql = SubscriberSeriesJdbcRepository.UPSERT_SQL;
            
            ChannelSftp sftp = null;
            try {
                sftp = (ChannelSftp) sftpSession.openChannel("sftp");
                sftp.connect();
                
                try (PreparedStatement ps = connection.prepareStatement(sql)) {
                    int batchCount = 0;
                    
                    // Process each file in the series
                    for (String fileName : files) {
                        String trimmedFileName = fileName.trim();
                        log.info("Processing series file: {}", trimmedFileName);
                        
                        try (InputStream sftpStream = sftp.get(trimmedFileName);
                             BufferedReader reader = new BufferedReader(new InputStreamReader(sftpStream, "UTF-8"))) {
                            
                            String line;
                            boolean isFirstLine = true;
                            Map<String, Integer> columnMap = null;
                            
                            while ((line = reader.readLine()) != null) {
                                // Parse header line to create column mapping
                                if (isFirstLine) {
                                    isFirstLine = false;
                                    columnMap = parseHeader(line);
                                    log.info("Header line for {}: {}", trimmedFileName, line);
                                    log.info("Column mapping for {}: {}", trimmedFileName, columnMap);
                                    continue;
                                }
                                
                                // Only count data lines, not header lines
                                totalRecords.incrementAndGet();

                                try {
                                    SubscriberSeries series = processLine(line, totalRecords.get(), columnMap);
                                    if (series != null) {
                                        ps.setLong(1, series.getSeriesStart());
                                        ps.setLong(2, series.getSeriesEnd());
                                        ps.setString(3, series.getOperator());
                                        ps.setString(4, series.getVirtualOperator());
                                        ps.addBatch();
                                        batchCount++;
                                        processedRecords.incrementAndGet();
                                        
                                        // Execute batch every 5000 records for optimal performance
                                        if (batchCount >= 5000) {
                                            ps.executeBatch();
                                            batchCount = 0;
                                            connection.commit(); // Commit frequently to avoid long transactions
                                        }
                                    } else {
                                        skippedRecords.incrementAndGet();
                                    }
                                } catch (Exception e) {
                                    errorRecords.incrementAndGet();
                                    if (errorRecords.get() <= 10) {
                                        log.error("Error processing line {} in file {}: {} - Exception: {}", 
                                                totalRecords.get(), trimmedFileName, line, e.getMessage(), e);
                                    } else if (errorRecords.get() % 100000 == 0) {
                                        log.error("Continuing errors at line {} in file {}: {} - Exception: {}", 
                                                totalRecords.get(), trimmedFileName, line, e.getMessage());
                                    }
                                }

                                // Log progress every 100K records
                                if (totalRecords.get() % 100_000 == 0) {
                                    log.info("Processed {} records across all files, {} valid, {} skipped, {} errors", 
                                            totalRecords.get(), processedRecords.get(), skippedRecords.get(), errorRecords.get());
                                }
                            }
                            
                            log.info("Completed processing file: {} - Records processed: {}", 
                                    trimmedFileName, processedRecords.get());
                            
                        } catch (Exception fileEx) {
                            log.error("Error processing series file: {}", trimmedFileName, fileEx);
                            throw fileEx;
                        }
                    }
                    
                    // Execute remaining batch
                    if (batchCount > 0) {
                        ps.executeBatch();
                    }
                    
                    connection.commit();
                    log.info("Successfully completed series processing with optimized batching");
                }
                
            } finally {
                if (sftp != null && sftp.isConnected()) {
                    sftp.disconnect();
                }
            }
        }

        long endTime = System.currentTimeMillis();
        long durationSeconds = (endTime - startTime) / 1000;
        
        log.info("Grouped series job completed in {} seconds ({} minutes)", 
                durationSeconds, durationSeconds / 60);
        log.info("Total records: {}, Processed: {}, Skipped: {}, Errors: {}", 
                totalRecords.get(), processedRecords.get(), skippedRecords.get(), errorRecords.get());
        
        // Update step contribution with statistics efficiently
        try {
            // Use reflection to set the counts directly for better performance
            java.lang.reflect.Field readCountField = contribution.getClass().getDeclaredField("readCount");
            readCountField.setAccessible(true);
            readCountField.set(contribution, totalRecords.get());
            
            java.lang.reflect.Field writeCountField = contribution.getClass().getDeclaredField("writeCount");
            writeCountField.setAccessible(true);
            writeCountField.set(contribution, processedRecords.get());
            
            java.lang.reflect.Field processSkipCountField = contribution.getClass().getDeclaredField("processSkipCount");
            processSkipCountField.setAccessible(true);
            processSkipCountField.set(contribution, skippedRecords.get());
            
            log.info("Updated Spring Batch statistics: Read={}, Write={}, ProcessSkip={}", 
                    totalRecords.get(), processedRecords.get(), skippedRecords.get());
                    
        } catch (Exception reflectionError) {
            log.warn("Could not update Spring Batch statistics via reflection: {}", reflectionError.getMessage());
            // Fallback to increment methods (less efficient but functional)
            contribution.incrementWriteCount(processedRecords.get());
            log.info("Fallback statistics update: Write={}, Actual Read={}, ProcessSkip={}", 
                    processedRecords.get(), totalRecords.get(), skippedRecords.get());
        }

        return RepeatStatus.FINISHED;
    }

    /**
     * Process a single CSV line and return SubscriberSeries object, or null if the line should be skipped.
     * Updated to use dynamic column mapping based on header names.
     */
    private SubscriberSeries processLine(String line, long lineNumber, Map<String, Integer> columnMap) throws Exception {
        String[] v = line.replaceAll("\\s", "").split(",", -1);

        // Get column indexes dynamically based on header names
        Integer areaIndex = columnMap.get("AREA");
        Integer serieInicialIndex = columnMap.get("SERIE_INICIAL");
        Integer serieFinalIndex = columnMap.get("SERIE_FINAL");
        Integer operadorIndex = columnMap.get("OPERADOR");
        // Try different possible column names for virtual operator
        Integer virtualOperatorIndex = columnMap.get("IDX"); // Last column in the CSV
        
        // Validate required columns exist
        if (areaIndex == null || serieInicialIndex == null || serieFinalIndex == null || operadorIndex == null) {
            throw new IllegalArgumentException("Missing required columns. Expected: AREA, SERIE_INICIAL, SERIE_FINAL, OPERADOR");
        }
        
        // Validate we have enough columns for all required indexes
        int maxRequiredIndex = Math.max(Math.max(areaIndex, serieInicialIndex), 
                                       Math.max(serieFinalIndex, operadorIndex));
        
        // Include optional columns in max index calculation if they exist
        if (virtualOperatorIndex != null) {
            maxRequiredIndex = Math.max(maxRequiredIndex, virtualOperatorIndex);
        }
        
        if (v.length <= maxRequiredIndex) {
            throw new IllegalArgumentException(String.format("Line [%s] Invalid number of columns: %d (expected at least %d) - SKIPPED", 
                    lineNumber, v.length, maxRequiredIndex + 1));
        }

        long seriesStart;
        long seriesEnd;
        String operator;

        // Format phone numbers with country code 52
        String area = v[areaIndex];
        String serieInicial = v[serieInicialIndex];
        String countryCode = "52";
        String formattedRangeStart = String.format("%s%s%s", countryCode, area, serieInicial);

        try {
            seriesStart = Long.parseLong(formattedRangeStart);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(String.format("Line [%s] Invalid series start - SKIPPED", lineNumber));
        }

        String serieFinal = v[serieFinalIndex];
        String formattedRangeEnd = String.format("%s%s%s", countryCode, area, serieFinal);
        try {
            seriesEnd = Long.parseLong(formattedRangeEnd);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(String.format("Line [%s] Invalid series end - SKIPPED", lineNumber));
        }

        // Format operator with zero-padding to 3 digits
        try {
            operator = String.format("%03d", Long.parseLong(v[operadorIndex]));
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(String.format("Line [%s] Invalid operator - SKIPPED", lineNumber));
        }

        // Get idx and virtual operator from CSV, with fallback defaults
        String idx = "";
        String virtualOperator = "";
        if (virtualOperatorIndex != null && virtualOperatorIndex < v.length) {
            String idxValue = v[virtualOperatorIndex].trim();
            if (!idxValue.isEmpty()) {
                idx = idxValue;
                virtualOperator = idxValue; // Use same value for both idx and virtualOperator
            }
        } else {
            log.debug("IDX column not found or out of bounds. Index: {}, Array length: {}", virtualOperatorIndex, v.length);
        }
        

        return SubscriberSeries.builder()
                .seriesStart(seriesStart)
                .seriesEnd(seriesEnd)
                .operator(operator)
                .virtualOperator(virtualOperator)
                .build();
    }

    /**
     * Parse CSV header line to create column name to index mapping
     */
    private Map<String, Integer> parseHeader(String headerLine) {
        Map<String, Integer> columnMap = new HashMap<>();
        String[] headers = headerLine.split(",", -1);
        
        for (int i = 0; i < headers.length; i++) {
            String columnName = headers[i].trim().toUpperCase();
            columnMap.put(columnName, i);
        }
        
        return columnMap;
    }

}
