/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ****************************************************************************/

package com.salesforce.mcg.datasync.batch.series;

import com.jcraft.jsch.ChannelSftp;
import com.jcraft.jsch.SftpException;
import com.salesforce.mcg.datasync.batch.RetryListeners;
import com.salesforce.mcg.datasync.exception.BusinessSkipException;
import com.salesforce.mcg.datasync.model.LineWithNumber;
import com.salesforce.mcg.datasync.model.SubscriberPortability;
import com.salesforce.mcg.datasync.model.SubscriberSeries;
import com.salesforce.mcg.datasync.repository.impl.SubscriberSeriesJdbcRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.SkipListener;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.StepExecutionListener;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.core.step.skip.SkipPolicy;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.batch.item.database.JdbcBatchItemWriter;
import org.springframework.batch.item.database.builder.JdbcBatchItemWriterBuilder;
import org.springframework.batch.item.file.FlatFileItemReader;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.InputStreamResource;
import org.springframework.core.task.TaskExecutor;
import org.springframework.transaction.PlatformTransactionManager;

import javax.sql.DataSource;
import java.io.InputStream;
import java.util.Set;

/**
 * Configuration class for the Subscriber Series batch job.
 * <p>
 * Defines beans for job, step, reader, processor, and writer.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-09
 */
@Configuration
@RequiredArgsConstructor
@Slf4j
public class SubscriberSeriesJobConfig {

    /**
     * Defines and builds the subscriber series Spring Batch Job.
     * Now supports processing multiple series files as separate steps within a single job.
     *
     * @param jobRepository             the job repository
     * @param transactionManager        transaction manager for step chunking
     * @param stepExecutionListener     step execution listener
     * @param subscriberSeriesReader    FlatFileItemReader bean for source reading
     * @param subscriberSeriesProcessor processor to parse and transform lines
     * @param subscriberSeriesWriter    JDBC batch writer bean
     * @param taskExecutor              task executor for concurrency
     * @return configured Job instance
     */
    @Bean(name = "subscriberSeriesJobBean")
    public Job subscriberSeriesJob(
            JobRepository jobRepository,
            PlatformTransactionManager transactionManager,
            StepExecutionListener stepExecutionListener,
            @Qualifier("gzSftpAwareReader") FlatFileItemReader<LineWithNumber> subscriberSeriesReader,
            ItemProcessor<LineWithNumber, SubscriberSeries> subscriberSeriesProcessor,
            JdbcBatchItemWriter<SubscriberSeries> subscriberSeriesWriter,
            SkipListener<LineWithNumber, SubscriberPortability> skipListener,
            RetryListeners retryListener,
            TaskExecutor taskExecutor) {

        Set<Class<? extends Throwable>> skippables = Set.of(
                BusinessSkipException.class
        );

        SkipPolicy unlimitedForSet = (t, count) ->
                skippables.stream().anyMatch(c -> c.isInstance(t));

        // Create a dynamic step that will handle multiple files
        Step multiFileImportStep = new StepBuilder("subscriberSeriesMultiFileImportStep", jobRepository)
                .tasklet(multiFileSeriesTasklet(), transactionManager)
                .listener(stepExecutionListener)
                .build();

        return new JobBuilder("subscriberSeriesJob", jobRepository)
                .start(multiFileImportStep)
                .build();
    }

    /**
     * Creates the MultiFileSeriesTasklet bean with proper dependency injection.
     *
     * @return configured MultiFileSeriesTasklet
     */
    @Bean
    public MultiFileSeriesTasklet multiFileSeriesTasklet() {
        return new MultiFileSeriesTasklet();
    }

    /**
     * Reader bean for reading subscriber series data from multiple SFTP resources.
     * Now supports processing multiple files passed as a comma-separated list.
     *
     * @param sftp       the SFTP channel
     * @param fileNames  comma-separated list of remote file paths
     * @return configured FlatFileItemReader
     * @throws SftpException if an error occurs during SFTP file retrieval
     */
    @Bean
    @StepScope
    public FlatFileItemReader<String> subscriberSeriesReader(
            ChannelSftp sftp,
            @Value("#{jobParameters[fileName]}") String fileNames) throws SftpException {

        // Handle multiple files - split by comma and process sequentially
        String[] files = fileNames.split(",");
        log.info("Processing {} series files: {}", files.length, java.util.Arrays.toString(files));
        
        // For now, we'll process the first file and log the others
        // TODO: Implement multi-file reader or create separate steps for each file
        String primaryFile = files[0].trim();
        log.info("Primary series file for this step: {}", primaryFile);
        
        if (files.length > 1) {
            log.info("Additional series files will be processed in subsequent steps: {}", 
                    java.util.Arrays.toString(java.util.Arrays.copyOfRange(files, 1, files.length)));
        }

        InputStream is = sftp.get(primaryFile);
        FlatFileItemReader<String> reader = new FlatFileItemReader<>();
        reader.setResource(new InputStreamResource(is));
        reader.setLineMapper((line, lineNumber) -> line);
        reader.setLinesToSkip(1);
        return reader;
    }

    /**
     * Processor for converting lines of file to SubscriberSeries model objects.
     *
     * @return an ItemProcessor that parses each line into a SubscriberSeries
     */
    @Bean
    public ItemProcessor<LineWithNumber, SubscriberSeries> subscriberSeriesProcessor() {
        return line -> {

            String[] v = line.getLine()
                    .replaceAll("\s", "")
                    .split(",", -1);

            if (v.length != 18) {
                throw new BusinessSkipException(String.format("Line [%s] Invalid number of columns - SKIPPED", line.getLineNumber()));
            }

            String countryCode = "52";
            String area = v[0];
            String seriesStartStr = v[1];
            String seriesEndStr = v[2];
            String operator = v[4];
            String virtualOperator = v[16];

            long seriesStart;
            try {
                seriesStart = Long.parseLong(countryCode + area + seriesStartStr);
            } catch (NumberFormatException e) {
                throw new BusinessSkipException(String.format("Line [%s] Invalid series start - SKIPPED", line.getLineNumber()));
            }

            long seriesEnd;
            try {
                seriesEnd = Long.parseLong(countryCode + area + seriesEndStr);
            } catch (NumberFormatException e) {
                throw new BusinessSkipException(String.format("Line [%s] Invalid series end - SKIPPED", line.getLineNumber()));
            }

            try {
                operator = String.format("%03d", Long.parseLong(operator));
            } catch (NumberFormatException e) {
                throw new BusinessSkipException(String.format("Line [%s] Invalid operator - SKIPPED", line.getLineNumber()));
            }

            if (v[5] != null) {
                try {
                    virtualOperator = String.format("%03d", Long.parseLong((v[5])));
                } catch (NumberFormatException e) {
                    throw new BusinessSkipException(String.format("Line [%s] Invalid virtual operator - SKIPPED", line.getLineNumber()));
                }
            }

            return SubscriberSeries.builder()
                    .seriesStart(seriesStart)
                    .seriesEnd(seriesEnd)
                    .operator(operator)
                    .virtualOperator(virtualOperator)
                    .build();

        };
    }

    /**
     * JDBC batch item writer bean for SubscriberSeries objects.
     *
     * @param dataSource datasource to connect to the target database
     * @return JdbcBatchItemWriter instance
     */
    @Bean
    public JdbcBatchItemWriter<SubscriberSeries> subscriberSeriesWriter(DataSource dataSource) {
        return new JdbcBatchItemWriterBuilder<SubscriberSeries>()
                .itemPreparedStatementSetter((item, ps) -> {
                    ps.setLong(1, item.getSeriesStart());
                    ps.setLong(2, item.getSeriesEnd());
                    ps.setString(3, item.getOperator());
                    ps.setString(4, item.getVirtualOperator());
                })
                .sql(SubscriberSeriesJdbcRepository.UPSERT_SQL)
                .dataSource(dataSource)
                .build();
    }
}