
/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 ***************************************************************************/
package com.salesforce.mcg.datasync.exception;

/**
 * Exception class used to indicate business logic conditions where an operation should be skipped.
 * <p>
 * This unchecked exception can be thrown to signal that a particular business scenario 
 * needs to be skipped without treating it as a system error.
 * 
 * @since 2024-06-07
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 */
public class BusinessSkipException extends RuntimeException {

    /**
     * Constructs a new {@code BusinessSkipException} with the specified detail message.
     *
     * @param message the detail message explaining the reason for the skip
     */
    public BusinessSkipException(String message) {
        super(message);
    }
}
