/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 *****************************************************************************/

package com.salesforce.mcg.datasync.batch.operator;

import com.jcraft.jsch.ChannelSftp;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.Session;
import com.jcraft.jsch.SftpException;
import com.salesforce.mcg.datasync.model.LineWithNumber;
import com.salesforce.mcg.datasync.model.Operator;
import com.salesforce.mcg.datasync.repository.impl.OperatorJdbcRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.batch.core.Job;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.StepExecutionListener;
import org.springframework.batch.core.configuration.annotation.StepScope;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.batch.item.database.JdbcBatchItemWriter;
import org.springframework.batch.item.database.builder.JdbcBatchItemWriterBuilder;
import org.springframework.batch.item.file.FlatFileItemReader;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.InputStreamResource;
import org.springframework.transaction.PlatformTransactionManager;

import javax.sql.DataSource;
import java.io.InputStream;

/**
 * Configuration class for Operator batch job.
 * Defines all necessary beans for reading, processing, and writing Operator records in a Spring Batch job.
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-06
 */
@Configuration
@RequiredArgsConstructor
public class OperatorJob {

    /**
     * Creates the Job bean for Operator import using multi-file tasklet.
     * Processes multiple operator files (1 per company) as a single grouped job.
     *
     * @param jobRepository         the job repository
     * @param transactionManager    the transaction manager
     * @param stepExecutionListener the step execution listener
     * @return the configured Job
     */
    @Bean(name = "operatorJobBean")
    public Job operatorJob(JobRepository jobRepository,
                           PlatformTransactionManager transactionManager,
                           StepExecutionListener stepExecutionListener) {

        Step multiFileImportStep = new StepBuilder("operatorMultiFileImportStep", jobRepository)
                .tasklet(multiFileOperatorTasklet(), transactionManager)
                .listener(stepExecutionListener)
                .build();

        return new JobBuilder("operatorJob", jobRepository)
                .start(multiFileImportStep)
                .build();
    }

    /**
     * Creates the MultiFileOperatorTasklet bean with proper dependency injection.
     *
     * @return configured MultiFileOperatorTasklet
     */
    @Bean
    public MultiFileOperatorTasklet multiFileOperatorTasklet() {
        return new MultiFileOperatorTasklet();
    }


    /**
     * Provides a FlatFileItemReader for reading operator data from a remote source via SFTP.
     *
     * @param session       the SFTP channel
     * @param remotePath the remote file name (from job parameters)
     * @return a configured FlatFileItemReader to read the remote file
     * @throws SftpException if there are issues reading from SFTP
     */
    @Bean
    @StepScope
    public FlatFileItemReader<String> operatorReader(Session session,
                                                     @Value("#{jobParameters['fileName']}") String remotePath) throws SftpException, JSchException {
        ChannelSftp sftp = (ChannelSftp) session.openChannel("sftp");
        sftp.connect();
        InputStream inputStream = sftp.get(remotePath);
        FlatFileItemReader<String> reader = new FlatFileItemReader<>();
        reader.setResource(new InputStreamResource(inputStream));
        reader.setLineMapper((line, lineNumber) -> line);
        reader.setLinesToSkip(1);
        return reader;
    }

    /**
     * Transforms CSV lines into Operator objects using field mapping.
     *
     * @return the line-to-Operator processor
     */
    @Bean
    public ItemProcessor<LineWithNumber, Operator> operatorProcessor() {
        return line -> {
            String[] values = line.getLine().split(",", -1);
            return Operator.builder()
                    .operator(values[0])
                    .name(values[1])
                    .type(values[2])
                    .rao(values[3])
                    .masterAccount(values[4])
                    .additionalMasterAccount(values[5])
                    .virtualOperator(values[6])
                    .dualOperator(values[7])
                    .masterAccount11(values[8])
                    .masterAccount16(values[9])
                    .masterAccountTelnor(values[10])
                    .idRvtaMayorista(values[11])
                    .idx(values[12])
                    .build();
        };
    }

    /**
     * Configures a JdbcBatchItemWriter for the Operator model.
     *
     * @param dataSource the datasource
     * @return the batch item writer
     */
    @Bean
    public JdbcBatchItemWriter<Operator> operatorWriter(DataSource dataSource) {
        return new JdbcBatchItemWriterBuilder<Operator>()
                .itemPreparedStatementSetter((item, ps) -> {
                    ps.setString(1, item.getOperator());
                    ps.setString(2, item.getName());
                    ps.setString(3, item.getType());
                    ps.setString(4, item.getRao());
                    ps.setString(5, item.getMasterAccount());
                    ps.setString(6, item.getAdditionalMasterAccount());
                    ps.setString(7, item.getVirtualOperator());
                    ps.setString(8, item.getDualOperator());
                    ps.setString(9, item.getMasterAccount11());
                    ps.setString(10, item.getMasterAccount16());
                    ps.setString(11, item.getMasterAccountTelnor());
                    ps.setString(12, item.getIdRvtaMayorista());
                    ps.setString(13, item.getIdx());
                })
                .sql(OperatorJdbcRepository.UPSERT_SQL)
                .dataSource(dataSource)
                .build();
    }
}