/*****************************************************************************
 * DISCLAIMER:
 * This code is provided "AS IS", without any express or implied warranties,
 * including, but not limited to, the implied warranties of merchantability,
 * fitness for a particular purpose, or non-infringement. Use of this code is
 * at your own risk. In no event shall the authors or copyright holders be
 * liable for any direct, indirect, incidental, special, exemplary, or
 * consequential damages (including, but not limited to, procurement of
 * substitute goods or services; loss of use, data, or profits; or business
 * interruption), however caused and on any theory of liability, whether in
 * contract, strict liability, or tort (including negligence or otherwise)
 * arising in any way out of the use of this code, even if advised of the
 * possibility of such damage.
 *****************************************************************************/

package com.salesforce.mcg.datasync.config;

/**
 * DataSyncApplication-wide constant values for Marketing Cloud Relay.
 *
 * <p>
 * This utility class provides string and integer constants used throughout the application,
 * such as header names, queue names, batch processing parameters, and status indicators.
 * </p>
 *
 * @author Rodrigo Costa (rodrigo.costa@salesforce.com)
 * @generated by AI
 * @since 2024-06-09
 */
public final class AppConstants {

    /**
     * HTTP header name for trace identifier.
     */
    public static final String X_TRACE_ID = "X-Trace-Id";

    /**
     * Default queue name used for processing.
     */
    public static final String DEFAULT_QUEUE_NAME = "heroku.api.queue";

    /**
     * Default batch size for bulk operations.
     */
    public static final int DEFAULT_BATCH_SIZE = 10;

    /**
     * Default interval for batch processing in seconds.
     */
    public static final int DEFAULT_BATCH_INTERVAL_SECONDS = 60;

    /**
     * Status representing a pending operation.
     */
    public static final String STATUS_PENDING = "PENDING";

    /**
     * Status representing a successfully delivered operation.
     */
    public static final String STATUS_DELIVERED = "DELIVERED";

    /**
     * Status representing a failed operation.
     */
    public static final String STATUS_FAILED = "FAILED";

    /**
     * Status representing a dropped operation.
     */
    public static final String STATUS_DROPPED = "DROPPED";

    /**
     * Private constructor to prevent instantiation.
     */
    private AppConstants() {
        // Utility class; prevent instantiation.
    }
}
